### ISSUE TITLE
Does not run on Ubuntu xenial

### ISSUE THREAD

**Issue by probonopd** [Lateralus138/MC-Chunk-Get-V2#1]
Hi @Lateralus138, thanks for making an AppImage. Currently it does not pass our automated test on Ubuntu xenial:

> libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /run/firejail/appimage/.appimage-9211/libpython3.6m.so.1.0)

Please use ingredients from Ubuntu xenial or older (or another distribution from the same time), but not a newer system. Glibc 2.25 is too new.

Reference: https://github.com/AppImage/appimage.github.io/pull/1913

**Comment by Lateralus138** [comment]
I'll look into it at some point, but isn't Xenial at the end of it's life? Sorry, but this is a personal project I did for fun & even the current LTS is old. I'm not saying I won't do something, it just might take me a while. I might have to install Xenial in a VM to build & test the project & that means I would have to do it on my desktop & I'm getting too old with too many back problems & so it might take me some time. Thanks for bringing it to my attention.

**Comment by probonopd** [comment]
Great personal project :+1: Ubuntu xenial is still supported until April 2021. For AppImages to pass our automated tests, they always need to run on the oldest still-supported LTS release of Ubuntu. The easiest way to build on xenial may be to use a CI service like Travis CI that can build for you on a server in the cloud without you needing to install anything on your local machine.

**Comment by Lateralus138** [comment]
Just an update: I have started working on this... Attempting a compile on a Xenial chroot before I try Travis CI as I've done plenty of chroot stuff, but have never messed with a Travis environment.

**Comment by Lateralus138** [comment]
I will be fixing this very soon; I already know what I need to do and it's on my ***TODO*** list in the next few days.
